finanzas/clients/urls.py
from django.urls import path

from .views import index
from .views import detail

app_name = 'clients'

urlpatterns = [
    path('', index, name='index'),
    path('detalles/<int:pk>', detail, name='detail'),
]

finanzas/finanzas/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index
from .views import dashboard

from .views import login
from .views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    
    path('login', login, name='login'),
    path('logout', logout, name='logout'),

    path('dashboard', dashboard, name='dashboard'), 
    path('creditos/', include('credits.urls')),
    path('clientes/', include('clients.urls')),
    path('usuarios/', include('users.urls')),
    path('carpetas/', include('folders.urls')),
    
    
    path('grupos/', include('groups.urls')),
]

finanzas/users/urls.py
from django.urls import path

from .views import index
from .views import create, update

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('nuevo/', create, name='create'),
    path('<int:pk>/actualizar/', update, name='update'),
]

finanzas/clients/models.py
from django.db import models

# Create your models here.

finanzas/prospects/models.py
from django.db import models

from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext_lazy as _


class Prospect(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    phone_number = models.BigIntegerField(null=True, blank=True)
    curp = models.CharField(max_length=18, null=True, blank=True)
    DNI = models.CharField(max_length=50, null=True, blank=True) 
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return f'{self.name} {self.last_name}'
    
    
    @property
    def full_name(self):
        return f'{self.name} {self.last_name}'


    @property
    def address(self):
        return self.addresses.first()


class Client(models.Model):
    
    class MARITAL_STATE_CHOICES(models.IntegerChoices):
        SINGLE = 0, _('Soltero(a)')
        MARRIED = 1, _('Casado(a)')
        DIVORCED = 2, _('Divorciado(a)')
        ENGAGGED = 3, _('Comprometido(a)')
        SINGLE_FATHER = 4, _('Padre Soltero(a)')
        WINDOWER = 5, _('Viudo(a)')
        FREE_UNION = 6, _('Unión Libre)')


    marital_state = models.IntegerField(choices=MARITAL_STATE_CHOICES.choices, default=0, null=False, blank=False) # ENUM # relationship status
    spouse = models.CharField(max_length=200, null=False, blank=False) # Conyugue
    job = models.CharField(max_length=200, null=False, blank=False)
    children = models.IntegerField(null=False, blank=False, default=0)
    prospect = models.OneToOneField(Prospect, on_delete=models.CASCADE, primary_key=True)
    
    note = models.TextField(null=True, blank=True, default='')
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.prospect.full_name}'
    
    
    @property
    def address(self):
        return self.prospect.addresses.first()
    

    @property
    def aval(self):
        return self.avals.first()
    
    
    @property
    def full_name(self):
        return f'{self.prospect.name} {self.prospect.last_name}'
    

    @property
    def marital_state_format(self):
        return Client.MARITAL_STATE_CHOICES.choices[self.marital_state][1]
    
    
    
    @property
    def credit(self):
        return self.credits.first()
    
    
    @property
    def lat(self):
        return self.prospect.address.lat    
    
    
    @property
    def long(self):
        return self.prospect.address.long
    
    
class Aval(models.Model):
    prospect = models.OneToOneField(Prospect, on_delete=models.CASCADE, primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='avals')
    
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.prospect.full_name}'
    
    
class ReferenceManager(models.Manager):
    
    def create_reference(self, client, data):
        from addresses.models import Address
        
        prospect = Prospect.objects.create(name=data['name'])
        address = Address.objects.create(address=data['address'], prospect=prospect)
        
        return self.create(
            client=client,
            prospect=prospect,
            relationship=data['relationship'],
            contact=data['contact']
        )
        

class Reference(models.Model):
    prospect = models.OneToOneField(Prospect, on_delete=models.CASCADE, primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='references')
    
    relationship = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    
    objects = ReferenceManager()
    
    
    def __str__(self):
        return f'{self.prospect.full_name}'

finanzas/clients/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404

from prospects.models import Client
from prospects.models import Prospect

def index(request):
    context = { 'title': 'Busqueda de clientes' }
    
    if request.method == 'GET' and request.GET.get('curp'):
        client = Client.objects.filter(prospect__curp=request.GET['curp']).first()
        
        if client and client.credit:
            context['client'] = client

    return render(request, 'clients/index.html', context)
            

def detail(request, pk):
    client = get_object_or_404(Client, pk=pk)
    
    return render(request, 'clients/detail.html', {
        'client': client,
        'lat': client.address.lat,
        'long': client.address.lat,
        'credits': client.credits.order_by('-id')
    })

finanzas/clients/templates/clients/snippets/card.html
<div class="w-full p-4">
  <div class="relative p-6 bg-gray-50 shadow rounded">
    <h3 class="text-left font-bold text-xl">{{ client.full_name }}</h3>
    <p class="mb-6 text-center text-sm text-gray-500">{{ client.prospect.job }}</p>
  
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">CURP</h4>
		  </div>
			<span>{{ client.prospect.curp }}</span>
		</p>
	</div>
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">Clave de elector</h4>
		  </div>
			<span>{{ client.prospect.DNI }}</span>
		</p>
	</div>
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">Número teléfonico</h4>
		  </div>
			<span>{{ client.prospect.phone_number }}</span>
		</p>
	</div>

    <a class="flex items-center justify-center py-2 text-sm text-white bg-indigo-500 hover:bg-indigo-600 rounded transition duration-200" href="{% url 'clients:detail' pk=client.pk %}">
      <span>Detalles</span>
    </a>
  </div>
</div>

finanzas/clients/templates/clients/snippets/prospect.html
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
        <!-- 
        <span class="inline-block mr-2">
            <svg width="16" height="18" viewBox="0 0 16 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4.66667 9.00002H6.33333C6.55435 9.00002 6.76631 8.91222 6.92259 8.75594C7.07887 8.59966 7.16667 8.3877 7.16667 8.16669C7.16667 7.94567 7.07887 7.73371 6.92259 7.57743C6.76631 7.42115 6.55435 7.33335 6.33333 7.33335H4.66667C4.44565 7.33335 4.23369 7.42115 4.07741 7.57743C3.92113 7.73371 3.83333 7.94567 3.83333 8.16669C3.83333 8.3877 3.92113 8.59966 4.07741 8.75594C4.23369 8.91222 4.44565 9.00002 4.66667 9.00002ZM12.1667 4.00002H8V2.33335H8.83333C9.05435 2.33335 9.26631 2.24556 9.42259 2.08928C9.57887 1.933 9.66667 1.72103 9.66667 1.50002C9.66667 1.27901 9.57887 1.06704 9.42259 0.910765C9.26631 0.754484 9.05435 0.666687 8.83333 0.666687H7.16667C6.94565 0.666687 6.73369 0.754484 6.57741 0.910765C6.42113 1.06704 6.33333 1.27901 6.33333 1.50002V4.00002H3.83333C2.94928 4.00002 2.10143 4.35121 1.47631 4.97633C0.851189 5.60145 0.5 6.4493 0.5 7.33335V12.3334C0.5 12.5544 0.587797 12.7663 0.744078 12.9226C0.900358 13.0789 1.11232 13.1667 1.33333 13.1667H6.33333V16.5C6.33333 16.721 6.42113 16.933 6.57741 17.0893C6.73369 17.2456 6.94565 17.3334 7.16667 17.3334C7.38768 17.3334 7.59964 17.2456 7.75592 17.0893C7.9122 16.933 8 16.721 8 16.5V13.1667H14.6667C14.8877 13.1667 15.0996 13.0789 15.2559 12.9226C15.4122 12.7663 15.5 12.5544 15.5 12.3334V7.33335C15.5 6.4493 15.1488 5.60145 14.5237 4.97633C13.8986 4.35121 13.0507 4.00002 12.1667 4.00002ZM8.83333 7.33335V11.5H2.16667V7.33335C2.16667 6.89133 2.34226 6.4674 2.65482 6.15484C2.96738 5.84228 3.39131 5.66669 3.83333 5.66669H9.3C8.99704 6.17001 8.8358 6.74589 8.83333 7.33335ZM13.8333 11.5H10.5V7.33335C10.5 6.89133 10.6756 6.4674 10.9882 6.15484C11.3007 5.84228 11.7246 5.66669 12.1667 5.66669C12.6087 5.66669 13.0326 5.84228 13.3452 6.15484C13.6577 6.4674 13.8333 6.89133 13.8333 7.33335V11.5Z" fill="#C2C9D2"></path>
            </svg>
        </span>
        -->
      <h4 class="text-lg text-gray-500">Nombre completo</h4>
    </div>
    <span class="text-lg">{{ prospect.full_name }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Número teléfonico</h4>
    </div>
    <span class="text-lg">{{ prospect.phone_number }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">CURP</h4>
    </div>
    <span class="text-lg">{{ prospect.curp }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Clave de elector</h4>
    </div>
    <span class="text-lg">{{ prospect.DNI }}</span>
</div>

<hr class="mt-4 mb-4">

<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Domicilio</h4>
    </div>
    <span class="text-lg">{{ address }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Colonia</h4>
    </div>
    <span class="text-lg">{{ address.suburb }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Municipio</h4>
    </div>
    <span class="text-lg">{{ address.township }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Estado</h4>
    </div>
    <span class="text-lg">{{ address.state_format }}</span>
</div>
<div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Código Postal</h4>
    </div>
    <span class="text-lg">{{ address.zip }}</span>
</div>

{% if customer %}
  <hr class="mt-4 mb-4">
  
  <div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Estado civil</h4>
    </div>
    <span class="text-lg">{{ customer.marital_state_format }}</span>
  </div>
  <div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Ocupación</h4>
    </div>
    <span class="text-lg">{{ customer.job }}</span>
  </div>
  <div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Nombre del conyugue</h4>
    </div>
    <span class="text-lg">{{ customer.spouse }}</span>
  </div>
  <div class="flex mb-4 justify-between items-center">
    <div class="flex items-center">
      <h4 class="text-lg text-gray-500">Número de hijos</h4>
    </div>
    <span class="text-lg">{{ customer.children }}</span>
  </div>

{% endif %}

finanzas/clients/templates/clients/snippets/reference.html
<div class="mb-3">
    <div class="flex items-center ">
        <h4 class="text-lg text-gray-500">Nombre</h4>
    </div>
    <span class="text-lg">{{ reference.client.full_name }}</span>    
</div>
<div class="mb-3">
    <div class="flex items-center ">
        <h4 class="text-lg text-gray-500">Contacto</h4>
    </div>
    <span class="text-lg">{{ reference.contact }}</span>    
</div>
<div class="mb-3">
    <div class="flex items-center ">
        <h4 class="text-lg text-gray-500">Dirección</h4>
    </div>
    <span class="text-lg">{{ reference.client.address }}</span>    
</div>
<div class="mb-3">
    <div class="flex items-center ">
        <h4 class="text-lg text-gray-500">Parentesco</h4>
    </div>
    <span class="text-lg">{{ reference.relationship }}</span>    
</div>

finanzas/clients/templates/clients/snippets/resume.html
<div class="w-full p-4">
  <div class="relative p-6 bg-slate-50 shadow rounded">
    <h3 class="text-left font-bold text-xl">{{ client.full_name }}</h3>
    <p class="mb-6 text-center text-sm text-gray-500">{{ client.prospect.job }}</p>
  
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">CURP</h4>
		  </div>
			<span>{{ client.prospect.curp }}</span>
		</p>
	</div>
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">Clave de elector</h4>
		  </div>
			<span>{{ client.prospect.DNI }}</span>
		</p>
	</div>
	<div class="mt-4 mb-4">
		<p class="flex items-center text-sm">
			<div class="flex items-center">
			<h4 class="text-sm text-gray-500">Número teléfonico</h4>
		  </div>
			<span>{{ client.prospect.phone_number }}</span>
		</p>
	</div>

    <a class="flex items-center justify-center py-2 text-sm text-white bg-indigo-500 hover:bg-indigo-600 rounded transition duration-200" href="{% url 'clients:detail' pk=client.pk %}">
      <span>Ver detalles del cliente</span>
    </a>
  </div>
</div>