finanzas/finanzas/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index
from .views import dashboard

from .views import login
from .views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    
    path('login', login, name='login'),
    path('logout', logout, name='logout'),

    path('dashboard', dashboard, name='dashboard'), 
    path('creditos/', include('credits.urls')),
    path('clientes/', include('clients.urls')),
    path('usuarios/', include('users.urls')),
    path('carpetas/', include('folders.urls')),
    
    
    path('grupos/', include('groups.urls')),
]

finanzas/folders/urls.py
from django.urls import path
from django.urls import include

from .views import create
from .views import FolderListView

app_name = 'folders'

urlpatterns = [
    path('', FolderListView.as_view(), name='list'),
    path('create', create, name='create'),
    
    path('<int:pk>/grupos', include('groups.urls')),
]

finanzas/users/urls.py
from django.urls import path

from .views import index
from .views import create, update

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('nuevo/', create, name='create'),
    path('<int:pk>/actualizar/', update, name='update'),
]

finanzas/folders/models.py
from django.db import models

class Folder(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    

finanzas/folders/views.py
import json

from django.urls import reverse

from django.http import JsonResponse
from django.views.generic.list import ListView
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import get_object_or_404


from .models import Folder

class FolderListView(ListView):
    model = Folder
    template_name = 'folders/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def get_queryset(self):
        return Folder.objects.all().order_by('-id')
    

@csrf_exempt
def create(request):
    response = dict()
    body = json.loads(request.body.decode('utf-8'))
    
    if request.method == 'POST' and body.get('name'):
        folder = Folder.objects.create(name=body['name']) 
        
        response['id'] = folder.id
        response['name'] = folder.name
        response['next_url'] = reverse('folders:list')
        
    return JsonResponse(response)



        

finanzas/folders/templates/folders/snippets/modal/form.html
<div id="modal" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed right-0 left-0 top-4 z-50 justify-center items-center h-modal md:h-full md:inset-0">
  <div class="relative px-4 w-full max-w-md h-full md:h-auto">
      <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          
          <div class="flex justify-end p-2">
              <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-toggle="modal">
                  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
              </button>
          </div>

          <form id="form" class="px-6 pb-4 space-y-6 lg:px-8 sm:pb-6 xl:pb-8" action="{% url 'folders:create' %}">
              <div>
                  <input type="name" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Nombre de la carpeta" required>
              </div>
              <button type="submit" class="w-full text-white bg-indigo-600 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">Crear carpeta</button>
          </form>

      </div>
  </div>
</div> 

<script>

  document.getElementById('form').addEventListener('submit', function(event){
    event.preventDefault();
    
    const form = event.target;
    const userInputField = form.elements['userInput'];

    const name = form.elements['name'];
    
    fetch(form.action, {
      method: 'POST',
      headers: {
        'Accept': 'application/json, text/plain, */*',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({name: name.value })
      }).then(res => res.json())
      .then(function(response){
        
        next_url = response['next_url'];
        window.location.href = next_url;

      });

  ;})

</script>