finanzas/finanzas/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index
from .views import dashboard

from .views import login
from .views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    
    path('login', login, name='login'),
    path('logout', logout, name='logout'),

    path('dashboard', dashboard, name='dashboard'), 
    path('creditos/', include('credits.urls')),
    path('clientes/', include('clients.urls')),
    path('usuarios/', include('users.urls')),
    path('carpetas/', include('folders.urls')),
    
    
    path('grupos/', include('groups.urls')),
]

finanzas/groups/urls.py
from django.urls import path
from django.urls import include

from .views import create
from .views import GroupListView
from .views import GroupDetailView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('detalles/<int:pk>', GroupDetailView.as_view(), name='detail'),
    
    path('crear/', create, name='create'),
    path('<int:group_pk>/creditos/', include('credits.urls')),
]

finanzas/users/urls.py
from django.urls import path

from .views import index
from .views import create, update

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('nuevo/', create, name='create'),
    path('<int:pk>/actualizar/', update, name='update'),
]

finanzas/groups/models.py
from django.db import models

from folders.models import Folder

class Group(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, related_name='groups')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

finanzas/groups/views.py
import json

from django.urls import reverse

from django.shortcuts import get_object_or_404

from django.http import JsonResponse

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.views.decorators.csrf import csrf_exempt

from .models import Group
from folders.models import Folder

class GroupListView(ListView):
    model = Group
    template_name = 'groups/list.html'

    def dispatch(self, request, *args, **kwargs):
        self.folder_pk = kwargs.get('pk')
        self.folder = get_object_or_404(Folder, pk=self.folder_pk)
        
        return super(GroupListView, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['folder'] = self.folder
        context['groups'] = self.object_list
        
        return context
    
    
    def get_queryset(self):
        return self.folder.groups.all().order_by('-id')


class GroupDetailView(DetailView):
    model = Group
    template_name = 'groups/detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

@csrf_exempt
def create(request, pk):
    
    response = dict()
    body = json.loads(request.body.decode('utf-8'))
    
    
    if request.method == 'POST' and body.get('name') and body.get('folder_id'):
        folder = get_object_or_404(Folder, pk=body['folder_id'])
        group = Group.objects.create(name=body['name'], folder=folder) 
        
        response['id'] = group.id
        response['name'] = group.name
        response['folder_id'] = folder.id
        
        response['next_url'] = reverse('folders:groups:list', kwargs={'pk':folder.pk})
        
    return JsonResponse(response)

finanzas/groups/templates/groups/snippets/group.html
<div class="flex justify-between items-center mb-2 p-4 bg-gray-50 rounded">
    <div class="flex items-center">
      <span class="inline-flex w-10 h-10 mr-3 justify-center items-center bg-purple-50 rounded">
        <svg width="16" height="20" viewBox="0 0 16 20" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M9 12H5C4.73478 12 4.48043 12.1054 4.29289 12.2929C4.10536 12.4804 4 12.7348 4 13C4 13.2652 4.10536 13.5196 4.29289 13.7071C4.48043 13.8946 4.73478 14 5 14H9C9.26522 14 9.51957 13.8946 9.70711 13.7071C9.89464 13.5196 10 13.2652 10 13C10 12.7348 9.89464 12.4804 9.70711 12.2929C9.51957 12.1054 9.26522 12 9 12ZM13 2H11.82C11.6137 1.41645 11.2319 0.910998 10.7271 0.552938C10.2222 0.194879 9.61894 0.00173951 9 0H7C6.38106 0.00173951 5.7778 0.194879 5.27293 0.552938C4.76807 0.910998 4.38631 1.41645 4.18 2H3C2.20435 2 1.44129 2.31607 0.87868 2.87868C0.316071 3.44129 0 4.20435 0 5V17C0 17.7956 0.316071 18.5587 0.87868 19.1213C1.44129 19.6839 2.20435 20 3 20H13C13.7956 20 14.5587 19.6839 15.1213 19.1213C15.6839 18.5587 16 17.7956 16 17V5C16 4.20435 15.6839 3.44129 15.1213 2.87868C14.5587 2.31607 13.7956 2 13 2ZM6 3C6 2.73478 6.10536 2.48043 6.29289 2.29289C6.48043 2.10536 6.73478 2 7 2H9C9.26522 2 9.51957 2.10536 9.70711 2.29289C9.89464 2.48043 10 2.73478 10 3V4H6V3ZM14 17C14 17.2652 13.8946 17.5196 13.7071 17.7071C13.5196 17.8946 13.2652 18 13 18H3C2.73478 18 2.48043 17.8946 2.29289 17.7071C2.10536 17.5196 2 17.2652 2 17V5C2 4.73478 2.10536 4.48043 2.29289 4.29289C2.48043 4.10536 2.73478 4 3 4H4V5C4 5.26522 4.10536 5.51957 4.29289 5.70711C4.48043 5.89464 4.73478 6 5 6H11C11.2652 6 11.5196 5.89464 11.7071 5.70711C11.8946 5.51957 12 5.26522 12 5V4H13C13.2652 4 13.5196 4.10536 13.7071 4.29289C13.8946 4.48043 14 4.73478 14 5V17ZM11 8H5C4.73478 8 4.48043 8.10536 4.29289 8.29289C4.10536 8.48043 4 8.73478 4 9C4 9.26522 4.10536 9.51957 4.29289 9.70711C4.48043 9.89464 4.73478 10 5 10H11C11.2652 10 11.5196 9.89464 11.7071 9.70711C11.8946 9.51957 12 9.26522 12 9C12 8.73478 11.8946 8.48043 11.7071 8.29289C11.5196 8.10536 11.2652 8 11 8Z" fill="#382CDD"></path>
        </svg>
      </span>

      <a href="{% url  'groups:detail' group.id %}">
        <div>
          <h4 class="text-sm font-medium">{{ group.name }}</h4>
          <p class="text-xs text-gray-500">Prestamos: {{ group.credits.count }}</p>
        </div>
      </a>
    </div>
    <div class="flex items-center">
      <a class="ml-auto mr-5 flex items-center py-2 px-3 text-xs text-white bg-blue-500 hover:bg-greemn-600 rounded"  href="{% url 'folders:groups:credits:create' pk=folder.pk group_pk=group.pk %}">
        <span>Nuevo Prestamo</span>
      </a>
      
      <a class="ml-auto flex ml-5 items-center py-2 px-3 text-xs text-white bg-green-500 hover:bg-greemn-600 rounded"  href="#">
        <span>Control de pagos</span>
      </a>

      <!-- 
      <span class="inline-block mr-3 py-1 px-2 bg-green-50 text-xs text-green-500 rounded-full">3 tasks</span>
      <a href="#">
        <svg width="16" height="4" viewBox="0 0 16 4" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M8 0.333344C7.67037 0.333344 7.34813 0.431092 7.07405 0.614228C6.79997 0.797363 6.58635 1.05766 6.4602 1.36221C6.33406 1.66675 6.30105 2.00186 6.36536 2.32516C6.42967 2.64846 6.5884 2.94543 6.82149 3.17852C7.05458 3.41161 7.35155 3.57034 7.67485 3.63465C7.99815 3.69896 8.33326 3.66596 8.63781 3.53981C8.94235 3.41366 9.20265 3.20004 9.38578 2.92596C9.56892 2.65188 9.66667 2.32965 9.66667 2.00001C9.66667 1.55798 9.49107 1.13406 9.17851 0.821499C8.86595 0.508939 8.44203 0.333344 8 0.333344ZM2.16667 0.333344C1.83703 0.333344 1.5148 0.431092 1.24072 0.614228C0.966635 0.797363 0.753014 1.05766 0.626868 1.36221C0.500722 1.66675 0.467717 2.00186 0.532025 2.32516C0.596334 2.64846 0.755068 2.94543 0.988156 3.17852C1.22124 3.41161 1.51822 3.57034 1.84152 3.63465C2.16482 3.69896 2.49993 3.66596 2.80447 3.53981C3.10902 3.41366 3.36931 3.20004 3.55245 2.92596C3.73559 2.65188 3.83333 2.32965 3.83333 2.00001C3.83333 1.55798 3.65774 1.13406 3.34518 0.821499C3.03262 0.508939 2.6087 0.333344 2.16667 0.333344ZM13.8333 0.333344C13.5037 0.333344 13.1815 0.431092 12.9074 0.614228C12.6333 0.797363 12.4197 1.05766 12.2935 1.36221C12.1674 1.66675 12.1344 2.00186 12.1987 2.32516C12.263 2.64846 12.4217 2.94543 12.6548 3.17852C12.8879 3.41161 13.1849 3.57034 13.5082 3.63465C13.8315 3.69896 14.1666 3.66596 14.4711 3.53981C14.7757 3.41366 15.036 3.20004 15.2191 2.92596C15.4023 2.65188 15.5 2.32965 15.5 2.00001C15.5 1.55798 15.3244 1.13406 15.0118 0.821499C14.6993 0.508939 14.2754 0.333344 13.8333 0.333344Z" fill="#67798E"></path>
        </svg>
      </a>
      -->
    </div>
</div>